iawia002/lux

extractors/iqiyi.go, extractors/mgtv.go, utils/utils.go
=> main: naming

downloader/downloader.go
=> defer both close and rename file

README.md
Corrected grammar on sentences throughout the README.
Also added a short descriptive introduction for newcomers
=> Revised and added sentences for clarity

README.md, extractors/youtube.go, extractors/youtube_test.go, utils/utils.go
=> extractors/youtube: support playlist download

config/config.go, downloader/downloader.go, extractors/bcy.go, extractors/bilibili.go, extractors/douyin.go, extractors/iqiyi.go, extractors/mgtv.go, extractors/pixivision.go, extractors/tumblr.go, extractors/universal.go, extractors/vimeo.go, extractors/youku.go, extractors/youtube.go, main.go, test/utils.go
see our discussion in #38
close #38 
TODO:
=> main: Support multiple formats

README.md, config/config.go, downloader/downloader.go, main.go, utils/utils.go
=> main: Support specifying output path and name

extractors/youtube.go
=> extractors/youtube: Audio only file

README.md, extractors/facebook.go, extractors/facebook_test.go, main.go
=> extractors/facebook: Add basic support

README.md, extractors/douyu.go, extractors/douyu_test.go, main.go
=> extractors/douyu: Add basic support

extractors/bcy.go, extractors/bilibili/bilibili.go, extractors/douyin.go, extractors/douyu.go, extractors/facebook.go, extractors/iqiyi.go, extractors/mgtv.go, extractors/pixivision.go, extractors/tumblr.go, extractors/vimeo.go, extractors/youku.go, extractors/youku_test.go, extractors/youtube/youtube.go, request/request.go, utils/utils.go
the algorithm comes from @JayXon, many thanks
add a new parameter(refer) for Request
close #53 #35
=> extractors: update youku api

README.md
rewrote the description for -i option for clarity.
rewrote the cookies section so it is easier to read.
fixed a small wording mistake
=> Made changes to readme.md

downloader/downloader.go, extractors/douyin.go, extractors/weibo.go, extractors/weibo_test.go, extractors/youku_test.go, extractors/youtube/youtube.go, extractors/youtube/youtube_test.go
=> extractors/youtube: Fix the problem of extracting 1080P format

request/request.go
=> request: auto retry

extractors/youtube/youtube.go, extractors/youtube/youtube_test.go
=> extractors/youtube: Some pages only have url_encoded_fmt_stream_map field

extractors/bilibili/bilibili.go
=> extractors/bilibili: Support multiple formats

extractors/bilibili/bilibili.go, extractors/pixivision_test.go, utils/utils.go
=> utils: ⬆️ title escaping rules

extractors/bcy.go, extractors/bilibili/bilibili.go, extractors/douyin.go, extractors/douyu.go, extractors/facebook.go, extractors/instagram.go, extractors/iqiyi.go, extractors/mgtv.go, extractors/miaopai.go, extractors/pixivision.go, extractors/tumblr.go, extractors/tumblr_test.go, extractors/twitter.go, extractors/vimeo.go, extractors/weibo.go, extractors/youku.go, extractors/youtube/youtube.go, request/request.go, utils/utils.go, utils/utils_test.go
=> extractors/mgtv: Adapt the new API

README.md, extractors/bilibili/bilibili.go, extractors/qq.go, extractors/qq_test.go, main.go
=> extractors/qq: Add support

extractors/bilibili/bilibili.go
=> extractors/bilibili: fix regex

extractors/miaopai_test.go, extractors/weibo_test.go, request/request.go
=> request: skip verify SSL certificate

config/config.go, extractors/youku.go, extractors/youku_test.go, main.go
=> extractors/youku: 🔧 ccode

extractors/youku.go, extractors/youku_test.go
=> extractors/youku: 🔧 multi-language video

README.md, extractors/iqiyi_test.go, extractors/le.go, extractors/le_test.go, main.go
=> extractors/le: Add support

extractors/instagram_test.go, extractors/qq.go, extractors/qq_test.go
=> extractors/qq: fix videos that only have one part

README.md, config/config.go, downloader/downloader.go, main.go, request/request.go
=> downloader: auto retry when the download failed

downloader/downloader.go, extractors/douyin.go, extractors/douyin_test.go, extractors/facebook_test.go, extractors/youtube/youtube.go
=> downloader: fix default format

extractors/bilibili/bilibili.go, extractors/bilibili/bilibili_test.go, extractors/bilibili/types.go
=> extractors/bilibili: adapt to more quality

extractors/facebook_test.go, extractors/qq.go, extractors/qq_test.go, request/request.go
=> extractors/qq: fix filename construction

README.md, extractors/youku_test.go, main.go, request/request.go
=> extractors/youku: ⬆️ default ccode

downloader/downloader.go, test/utils.go
=> downloader: remove the default format

extractors/weibo/weibo.go, extractors/weibo/weibo_test.go
=> extractors/weibo: 🔧 weibo tv

README.md, extractors/yinyuetai/types.go, extractors/yinyuetai/yinyuetai.go, extractors/yinyuetai/yinyuetai_test.go, main.go
Hi, it's me again.
As you may guess, I'm working on downloading MVs these days. 
So here is an extractor for 音悦台.
=> Add, extractors for yinyuetai

README.md, config/config.go, extractors/youtube/youtube.go, extractors/youtube/youtube_test.go, main.go
=> extractors/youtube: option to use data in url_encoded_fmt_stream_map

downloader/downloader_test.go, extractors/bcy/bcy_test.go, extractors/iqiyi/iqiyi.go, extractors/iqiyi/iqiyi_test.go, extractors/miaopai/miaopai_test.go, extractors/vimeo/vimeo_test.go, extractors/weibo/weibo_test.go, extractors/yinyuetai/yinyuetai_test.go, extractors/youku/youku_test.go, extractors/youtube/youtube_test.go
=> extractors/iqiyi: switch to new algorithm

downloader/downloader.go, extractors/bilibili/bilibili.go, extractors/bilibili/bilibili_test.go, extractors/bilibili/types.go
=> extractors/bilibili: refactor data extraction

extractors/bcy/bcy.go, extractors/bcy/bcy_test.go, extractors/bilibili/bilibili.go, extractors/mgtv/mgtv_test.go
=> extractors/bilibili: update appkey and secret

README.md, config/config.go, downloader/downloader.go, extractors/twitter/twitter_test.go, extractors/youku/youku_test.go, main.go
fix #344 
fix #341 
fix #268 
fix #143 
fix #128
=> main: HTTP chunk size option

README.md
Hi, I added annie to Chocolatey: https://chocolatey.org/packages/annie (and I'll maintain the package going forward).
=> README: add Chocolatey instructions

extractors/pornhub/pornhub.go, extractors/pornhub/pornhub_test.go, main.go
Adding support to download videos from pornhub.
=> Pornhub Support

extractors/miaopai/miaopai.go, extractors/miaopai/miaopai_test.go, extractors/netease/netease_test.go, extractors/pornhub/pornhub.go, extractors/weibo/weibo_test.go, extractors/yinyuetai/yinyuetai_test.go, extractors/youtube/signature.go, extractors/youtube/youtube.go, extractors/youtube/youtube_test.go, test/utils.go
=> extractors/youtube: fix 403 error and signature algorithm

Gopkg.lock, Gopkg.toml, extractors/bcy/bcy_test.go, extractors/douyin/douyin_test.go, extractors/douyu/douyu_test.go, extractors/geekbang/geekbang_test.go, extractors/pornhub/pornhub.go, extractors/qq/qq_test.go, extractors/youtube/youtube.go, utils/utils.go, utils/utils_test.go, vendor/github.com/tidwall/gjson/LICENSE, vendor/github.com/tidwall/gjson/gjson.go, vendor/github.com/tidwall/gjson/gjson_gae.go, vendor/github.com/tidwall/gjson/gjson_ngae.go, vendor/github.com/tidwall/match/LICENSE, vendor/github.com/tidwall/match/match.go, vendor/github.com/tidwall/pretty/LICENSE, vendor/github.com/tidwall/pretty/pretty.go
Fix the issue for getting the title of youtube video
maybe need to update the file Gopkg.toml or Gopkg.lock
=> Fix the issue for getting the title of youtube video

downloader/downloader.go, extractors/bilibili/bilibili.go, utils/utils.go, utils/utils_test.go
fixes #451 
fixes #522 
closes #526
=> Fix filename issue caused by LimitLength

utils/download.go, utils/download_test.go
=> you can now select playlist areas like 1-7, 8-20

extractors/bilibili/bilibili.go, extractors/bilibili/types.go
=> extractors/bilibili: update the type of Aid

README.md, extractors/tiktok/tiktok.go, extractors/tiktok/tiktok_test.go, main.go
Relatively simple implementation. Just grabs the url and title from the html and downloads it.
Tested with both tiktok's shorter urls and normal urls.
=> Add TikTok support

README.md, config/config.go, main.go, request/request.go
=> request: respect HTTP proxy environment variables and drop support for setting proxy by options

README.md, config/config.go, extractors/bilibili/bilibili.go, main.go
=> Bilibili playlist episode can now be downloaded without the playlist title

extractors/geekbang/geekbang.go, extractors/geekbang/geekbang_test.go, extractors/miaopai/miaopai.go
=> extractors/geekbang: Renewed support

extractors/youtube/youtube.go
Should be fWebmLow instead of fM4aLow
=> fix a typo

downloader/downloader.go
fix #657 
close #665 
cc @M1178475702
=> downloader: using QuoteMeta wraps the filename

extractors/pornhub/pornhub.go, go.mod, go.sum
Need to run javascript in order to get the media urls.
Fixes #663 and #540
=> extractors: fix pornhub

extractors/bilibili/bilibili.go, extractors/types/types.go
=> extractors/bilibili: fix the cookie issue

downloader/downloader.go, downloader/downloader_test.go, extractors/instagram/instagram_test.go
=> downloader: use the correct referer

extractors/weibo/weibo.go, extractors/weibo/weibo_test.go
Add support for video.h5.weibo.cn, as requested by #576.
Add the corresponding test.
=> Support site: video.h5.weibo.cn

extractors/qq/qq.go
Change CDN selection method as the old one sometimes does not work well.
Related comments: 
https://github.com/iawia002/annie/pull/725#issuecomment-660042258
https://github.com/iawia002/annie/pull/725#issuecomment-660044127
=> fix(extractors/qq): Change CDN selection

README.md, cookier/cookier.go, cookier/cookier_test.go, go.mod, go.sum, main.go
Continue the #817.
Because I accidentally removed the fork.
=> feat: auto grab cookies from the user's Chrome or Edge

extractors/bilibili/bilibili.go
which produces broken json output
untested
=> print warning to stderr

README.md, main.go
Resolves #911 
close #784
close #644
close #596
=> Break the chunk size to 1

.github/workflows/builder.yml
Build binary and upload [artifacts](https://github.com/warcbot/annie/actions/runs/1042057075)
Copied from [github.com/wabarc/wayback](https://github.com/wabarc/wayback/blob/main/.github/workflows/builder.yml)
Ref #912
=> Add builder workflow

extractors/extractors.go, extractors/iqiyi/iqiyi.go, extractors/iqiyi/iqiyi_test.go
iqiyi.com redirect to iq.com now
=> fix iqiyi extractor

extractors/bilibili/bilibili.go, extractors/bilibili/bilibili_test.go, extractors/bilibili/types.go
=> extractors/bilibili: adopt the new API

extractors/douyin/douyin.go
=> 参照Issue #961修改了抖音解析逻辑

extractors/types/types.go
=> Fix json output

README.md, downloader/downloader.go, extractors/extractors.go, extractors/types/types.go, extractors/ximalaya/types.go, extractors/ximalaya/ximalaya.go, extractors/ximalaya/ximalaya_test.go
Add support for ximalaya, download audio by url.
Potential future improvement: download album.
=> Add support for ximalaya

extractors/pornhub/pornhub.go, extractors/types/defs.go, go.mod, go.sum
=> fix: pornhub extractor

downloader/downloader.go
Data race at:
```
WARNING: DATA RACE
Read at 0x00c0003e3710 by goroutine 76:
github.com/iawia002/lux/downloader.(*Downloader).multiThreadSave.func1()
/home/runner/go/pkg/mod/github.com/iawia002/lux@v0.12.1-0.20220209040223-671d8850a3a6/downloader/downloader.go:377 +0x7da
Previous write at 0x00c0003e3710 by goroutine 83:
github.com/iawia002/lux/downloader.(*Downloader).multiThreadSave.func1()
/home/runner/go/pkg/mod/github.com/iawia002/lux@v0.12.1-0.20220209040223-671d8850a3a6/downloader/downloader.go:377 +0x879
```
=> Thread-safe for collect error

extractors/tiktok/tiktok.go, extractors/tiktok/tiktok_test.go
=> fix: tiktok extractors

extractors/bilibili/bilibili.go, extractors/bilibili/types.go
=> Add durl to stream map

.github/workflows/stream_vk.yml, README.md, app/register.go, extractors/vk/vk.go, extractors/vk/vk_test.go
Add [vk.com](https://vk.com) extractor for videos.
=> Add vk extractor.

app/app.go
The latest youku-ccode is 0502, 
you can find it at <https://g.alicdn.com/kplayer/kuplayer/4.1.61-xmedia/index.js>.
=> Update Youku ccode

extractors/vimeo/vimeo.go
=> Treats vimeoProgressive.request.files.progressive.profile as type string

extractors/tiktok/tiktok.go, extractors/tiktok/tiktok_test.go
fix tiktok title error, and update tiktok_test.go
=> fix tiktok title

extractors/douyin/douyin.go, extractors/douyin/types.go
旧的API失效了，换了新的接口，换完发现douyin/types.go里面很多都变了，一个个比对太费事了，直接重写了
fix #1184
=> 更换抖音API（根据#1184）

extractors/bilibili/bilibili.go, extractors/bilibili/bilibili_test.go, extractors/bilibili/types.go
fix #1213 
fix #1214 
fix #1216
=> fix: bilibili extractBangumi

Cask.toml
Update the Windows URL.
fix #1240
=> Update Cask URL

extractors/douyin/types.go
"https://v.douyin.com/i8rV35QW/"  Interval 不一定都是int
fix #1301
=> Update douyinData types.go

downloader/downloader.go
=> feat: support bilibili audio only download

extractors/bilibili/bilibili.go, extractors/bilibili/types.go
=> 临时修复B站EP视频无法下载
