iawia002/lux

main.go

Helpful error message on few arguments

---

utils/utils.go

utils.FileName function uses strings.replacer instead of calling strings.replace multiple times

replaced strings.Replace() with strings.NewReplacer()

---

README.md

Missing punctuation marks. Add "then" to clause that tails "if" clause.

Fixed grammatical errors and sentence structures

---

.gitignore
.goreleaser.yml
compress.bat
compress.sh

The binary size of release page is too big, so I recommend using goreleaser instead of gox.

Using goreleaser instead of gox

---

downloader/downloader.go
extractors/bcy_test.go
extractors/bilibili/bilibili.go
extractors/instagram_test.go
utils/utils.go
utils/utils_test.go

utils: Handle overly long strings

---

.travis.yml
README.md
config/config.go
extractors/bilibili/bilibili.go
extractors/facebook.go
extractors/youtube/youtube.go
main.go
utils/download.go
utils/download_test.go
utils/utils.go
utils/utils_test.go

main: Specify the download range of the list

---

extractors/iqiyi.go
extractors/miaopai_test.go
extractors/weibo_test.go
extractors/youku_test.go

extractors/iqiyi: 🔧 tvid, vid and title

---

README.md
config/config.go
downloader/downloader.go
extractors/bilibili/bilibili.go
main.go
request/request.go

downloader: download captions

---

.gitignore
config/config.go
downloader/downloader.go
main.go

There are several reports about the download speed would slow down gradually, especially in Bilibili:
https://github.com/iawia002/annie/issues/275 https://github.com/iawia002/annie/issues/143 https://github.com/iawia002/annie/issues/128
I am not an expert in Go and have no idea to improve the application itself. So I tried to use third-party applications to download.
[aria2](https://aria2.github.io) is a very famous and lightweight command-line download utility. It has an interface of RPC, which means we can merely send a request to make it work.
```
-aria2
Use Aria2 RPC to download
-aria2addr string
Aria2 Address (default "localhost:6800")
-aria2method string
Aria2 Method (default "http")
-aria2token string
Aria2 RPC Token
```
Here is the demo:
- Use built-in download:
- Use aria2c (I …

Add support for Aria2 RPC

---

README.md
config/config.go
downloader/downloader.go
extractors/youku/youku_test.go
test/utils.go

continue #284
cc @hguandl, I have not changed the main logic, just move the part to the right place.

downloader: ⬆️ aria2

---

extractors/youtube/youtube_test.go
main.go

Avoid the following:
```
$ annie -i -p "    https://www.bilibili.com/bangumi/play/ep198061    "
Downloading     https://www.bilibili.com/bangumi/play/ep198061     error:
parse     https://www.bilibili.com/bangumi/play/ep198061    : invalid URI for request
```
```
$ annie "   https://img9.bcyimg.com/drawer/15294/post/1799t/1f5a87801a0711e898b12b640777720f.jpg   "
Downloading    https://img9.bcyimg.com/drawer/15294/post/1799t/1f5a87801a0711e898b12b640777720f.jpg    error:
parse    https://img9.bcyimg.com/drawer/15294/post/1799t/1f5a87801a0711e898b12b640777720f.jpg   : invalid URI for request
```
```
$ cat video.txt
https://www.bilibili.com/video/av21877586
https://www.bilibili.com/video/av21990740  
$ annie -F video.txt
Downloading     https://www.bilibili.com/video/av21877586   error: …
```

Trim spaces for video links.

---

config/config.go
downloader/downloader.go
downloader/downloader_test.go
main.go

Use chunk by chunk download to avoid cdn throttle the download.
it should be able to apply to other websites, but I don't have chances to test it.

fix for #341 -- only test for qq, I don't have chance to test other websites.

---

README.md
config/config.go
extractors/youku/youku.go
main.go

extractors/youku: add password option

---

downloader/downloader.go

Output names set to the same file name for every part would cause overrwrite while downloading different parts.  
And filename will be out of order even if set `max-concurrent-downloads=1` and disable `continue` option.

Fix wrong output name while Aria2 RPC calling

---

README.md
extractors/geekbang/geekbang.go
extractors/geekbang/geekbang_test.go
main.go

支持极客时间的视频下载，例如地址：https://time.geekbang.org/course/detail/190-97203
```
➜  annie git:(master) go run main.go -i https://time.geekbang.org/course/detail/190-97203
Site:      极客时间 geekbang.org
Title:     02 | 内容综述 - 玩转webpack
Type:      video
Streams:   # All available quality
[hd]  -------------------
Size:            36.42 MiB (38193140 Bytes)
[sd]  -------------------
Size:            19.83 MiB (20790544 Bytes)
[ld]  -------------------
Size:            12.08 MiB (12669884 Bytes)
```

extractors/geekbang: Add basic support

---

README.md
config/config.go
extractors/pornhub/pornhub_test.go
main.go
utils/download.go
utils/download_test.go
utils/utils.go
utils/utils_test.go

Closes #529 
Merged all commits into one 
@iawia002

You can now specify what URLs you want to download in a file

---

extractors/defs.go
extractors/youtube/youtube.go

some youtube page need user login.
guest will see
```
Sign in to confirm your age
This video may be inappropriate for some users.
```
and the HTML content will have this:
```
"playabilityStatus":{"status":"LOGIN_REQUIRED","reason":"Sign in to confirm your age","errorScreen":{"playerErrorMessageRenderer":{"subreason":{"runs":[{"text":"This video may be inappropriate for some users."}]},"reason":{"simpleText":"Sign in to confirm your age"}
```
we should notify the user the real reason so that they can have the -c param to load cookies.
not just print `url parse failed` , this does not help
ps:
an example URL:
```
https://www.youtube.com/watch?v=VJdCvboSmR4
```

youtube: detect login required video

---

main.go

I try to use cookie file with option -c but get error 
> net/http: invalid header field value "xxx\n" for key Cookie
After checking, error comes from [here](https://github.com/golang/go/blob/release-branch.go1.13/src/net/http/transport.go#L476), and the reason is vim adds new line at the end of file by default: https://stackoverflow.com/questions/14171254/why-would-vim-add-a-new-line-at-the-end-of-a-file

main: trim spaces in config.Cookie

---

downloader/downloader.go
extractors/youtube/youtube.go
utils/ffmpeg.go

Currently adaptive Youtube video streams (without sound) are merged with an audio m4a stream. This creates at least 2 issues:
1. Webm video streams are merged with the m4a audio stream inside an mp4 container. The resulting video does not show up in VLC or Windows Media Player, for instance (only the sound works). Webm video streams (vp8, vp9) should be merged only with webm audio (opus, vorbis) inside an webm container.
2. Audio only streams are also merged with the m4a stream inside an mp4 container, making the file at least twice as large. In this case only the audio stream should be downloaded (without merging it with the m4a stream).
The code in this pull request finds separate m4a and webm audio streams for videos in AdaptiveFormats and then merges them depending on the type of …

Youtube merge streams issues

---

config/config.go
downloader/downloader.go
downloader/types.go
main.go
utils/utils.go

1. 使用-m 参数启用多线程下载，线程数量由-n决定
2. 代码上是增加Save的可选版本MultiThreadSave版本。与进度条兼容。
3. MultiThreadSave的实现：
将文件分成指定的thread数量的part文件，每个part
文件记录着在整个文件中的偏移量，以及本part当前已下载的数据大小。恢复下载时，会同意所有part的信息，以支持继续下载。
当重新启动后，part数量与线程数量不同时，有以下两种情况：
1. 线程数量小于现存part数，则按线程池调度去完成所有part（使用信号量控制）
2. 线程数大于现存part数，则多于的线程不启用。
下载完成后，合并所有part，然后删除part文件（因此可能需要两倍大小的磁盘容量，回续可能优化）
线程调度方案也可能会优化，以尽量利用可能的线程

增加了当下载视频时，多线程分段下载的功能

---

README.md

So that the older, annie-compatible version of github.com/rylio/ytdl is used
fix #664

README.md: added GO111MODULE=on to go get

---

extractors/qq/qq.go

The old method of getting filename is invalid in some cases. 
Encapsulate the getting video information method into a function.
Fix #723

extractors: fix qq video, issue #723

---

extractors/weibo/weibo.go
extractors/weibo/weibo_test.go

Weibo TV has updated its API, the old weibo extractor is invalid for "weibo.com/tv/show/*"-like URLs. (#727)
Update extractor logics, also the test.
fix #727

Weibotv patch

---

downloader/downloader.go
extractors/bilibili/bilibili.go
extractors/bilibili/bilibili_test.go
extractors/bilibili/types.go

The old interface is not valid for getting 4K format(#670) or some URL(#716).
Some users also reported that using DASH API to download might be faster. (#684 )
Change the API to the latest DASH API;
Update the extract method for bilibil;
**4K Test**
annie -c cookies.txt -i https://www.bilibili.com/video/av412909688
```
Site:      哔哩哔哩 bilibili.com
Title:     【何同学4K】3299真香？iPhone SE使用体验
Type:      video
Streams:   # All available quality
[120]  -------------------
Quality:         超清 4K
Size:            275.73 MiB (289127402 Bytes)
[112]  -------------------
Quality:         高清 1080P+
Size:            208.00 MiB (218105640 Bytes)
[80]  -------------------
Quality:         高清 1080P
Size:            29.26 MiB (30676328 Bytes)
[64]  -------------------
Quality:         高清 720P
Size: …
```

Bilibili dash&4K

---

extractors/qq/qq.go

As mentioned in this [PR](https://github.com/iawia002/annie/pull/725#issuecomment-656511671), the request for key sometimes would retrieve 403 HTTP status. 
Change the referer header to empty in the request for video key is valid.

fix(extractors/qq): CDN as referer is invalid to the request for vkey.

---

extractors/weibo/weibo.go

The validation of the number of formats is not applicable for some videos.
Remove it as it is unnecessary.

fix(extractors/weibo): some videos dont have multi formats to select #742

---

downloader/downloader.go
extractors/bilibili/bilibili.go
extractors/bilibili/bilibili_test.go
extractors/bilibili/types.go
extractors/types/types.go
extractors/youtube/youtube.go

1. DASH API might return the non-separated file, i.e., mp4 and flv, but no m4s files.
2. Using an extra attribute to check if the stream parts need to be muxed into one mp4 file.
3. For some videos, the real resolution and the showing resolution are not matched. 
For example, in this URL (https://www.bilibili.com/video/BV1Hx411U7xL?p=4), 1080p and 720p files are 960*540 in fact (from [MediaInfo](https://mediaarea.net/en/MediaInfo)). By testing the videos on the browser side (Chrome and Firefox), the problem is the same. Since I do not familiar with the old API, might somebody help to test the old API on these videos?

fix(extractors/bilibili): Change the parsing method for some videos

---

extractors/bilibili/bilibili.go

下载bilibili playlist时，annie默认采用多线程。在Bilibili更新风控策略后，此类多线程下载被视为爬虫，从而导致用户ip被加入黑名单。ip加入黑名单期间，用户访问目标视频将返回http 412错误。
本次修改思路为：在下载bilibili视频时强制使用单线程。在解析bilibili视频时，强制忽略-n 参数，将下载线程数置为1。经测试，可以有效避免返回http 412错误。

fix issue #791 #782

---

extractors/bilibili/bilibili.go
extractors/bilibili/bilibili_test.go

* fix low quality audio issue #790
* fix incorrect muxed video size info bug introduced in e463c203f9956c14a6230e513af1cea0e0598bb1

extractors/bilibili: fix low quality audio issue #790 and incorrect muxed video size info bug

---

extractors/haokan/haokan.go
extractors/haokan/haokan_test.go

好看视频先前的视频地址位于 `video` 标签下，现在已经改为放在了 `JSON` 数据里，所以调整一下解析方式，改为两种都支持。
测试通过：

adjust haokan url parsing

---

main.go
utils/utils.go

This PR focuses on the colorized outputs in Windows CMD and PowerShell.
*But I'm not sure if it will break on non-Windows system. I have only tested on my windows and centos.*
`annie -v` doesn't print the colorized version info correctly in Windows CMD and PowerShell, but other commands such as `annie -i` works well.
- CMD
- PowerShell
- `annie -v` calls `PrintVersion()` to print version info:
https://github.com/iawia002/annie/blob/d0d473ae01e75b83a14066a37ab85da6a1a0f3c0/utils/utils.go#L258-L266
- `annie -i` calls `printStream()` to print stream info:
https://github.com/iawia002/annie/blob/d0d473ae01e75b83a14066a37ab85da6a1a0f3c0/downloader/utils.go#L40-L50
In `PrintVersion()` , CMD can't handle escape sequence strings provided by `cyan/blue.Sprintf()` . However, in `printStream()` , …

fix(utils/utils): use color.Output to handle escape sequence on Windows

---

request/request.go

The `Body` of `res` in `request.Headers` is not closed properly and this might cause the leak of HTTP connections

Fix connection leak

---

extractors/bilibili/bilibili.go
extractors/bilibili/types.go

I try to download https://www.bilibili.com/bangumi/play/ep366031 at bilibili, but it failed:
```
URL:         https://api.bilibili.com/pgc/player/web/playurl?cid=258893183&bvid=&qn=120&type=&otype=json&fourk=1&fnver=0&fnval=16
Method:      GET
Headers:     http.Header{
"Accept-Language": {"en-US,en;q=0.8"},
"User-Agent":      {"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.81 Safari/537.36"},
"Accept":          {"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"},
"Accept-Charset":  {"UTF-8,*;q=0.5"},
"Accept-Encoding": {"gzip,deflate,sdch"},
"Referer":         {"https://www.bilibili.com"},
}
Status Code: 200
Downloading https://www.bilibili.com/bangumi/play/ep366031 error: …
```

add bvid resolving at bilibili

---

README.md
extractors/acfun/acfun.go
extractors/acfun/acfun_test.go
extractors/acfun/types.go
extractors/extractors.go
go.mod
go.sum
request/request.go

#397 add acfun bangumi download support, but normal videos are __not__ supported yet
* Cause acfun use m3u8 format file, it is hard to calculate the video size, so I omitted it.
* Change parameter ```http.MethodGet``` at ```Header``` method into ```http.MethodHead```
* [Limit display of parts](https://github.com/closetool/annie/blob/acfun/extractors/types/types.go#L21)

Acfun extractor

---

request/request.go

向 Bilibili 发送 HEAD 请求时会返回 400 错误，改回 GET 请求来确保兼容性。
fix #881 
fix #843

Bilibili 不支持 HEAD 请求，改回 GET 请求

---

extractors/extractors.go

```bash
annie: version 0.10.3, A fast, simple and clean video downloader.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x8b8265]
goroutine 1 [running]:
github.com/iawia002/annie/extractors.Extract(0x7ffeeb72af43, 0x13, 0x0, 0x0, 0x0, 0x1, 0x0, 0xa, 0x0, 0x0, ...)
/Users/mac/iawia002/go/src/github.com/iawia002/annie/extractors/extractors.go:104 +0x2f5
main.download(0x7ffeeb72af43, 0x13, 0x1, 0x1)
/Users/mac/iawia002/go/src/github.com/iawia002/annie/main.go:131 +0x18d
main.main()
/Users/mac/iawia002/go/src/github.com/iawia002/annie/main.go:253 +0x26d
```
Related issues:
- iawia002/annie#852
- iawia002/annie#814
- iawia002/annie#794
- iawia002/annie#760
- iawia002/annie#754
fix #852
fix #814
fix #794
fix …

Fix nil pointer dereference

---

utils/utils.go

当我使用`-F file.txt`读取文件中的地址下载`bilibili`分P视频时，文件中的第一个视频总是会被跳过，就像下面这个文件一样：
```
https://www.bilibili.com/video/BV1UW411x7v2?p=1
https://www.bilibili.com/video/BV1UW411x7v2?p=2
https://www.bilibili.com/video/BV1UW411x7v2?p=3
```
我通过文档了解到`start`默认值为1，但是加上`-start 0`也会跳过第一个视频，随即我查看源代码并修复，增加并通过了测试用例。
When I use `-F file.txt` to read the address in the file to download `bilibili` split-P videos, the first video in the file is always skipped, as in the following file.
```
https://www.bilibili.com/video/BV1UW411x7v2?p=1
https://www.bilibili.com/video/BV1UW411x7v2?p=2
https://www.bilibili.com/video/BV1UW411x7v2?p=3
```
I learned from the documentation that `start` defaults to 1, but adding `-start 0` also skips the first video, so I then looked at the source code and fixed it, added and passed the test …

fix: the start parameter does not take effect

---

README.md

Rather than quoting the URL case by case, it's a better practice to always quote them. Other video downloaders like [youtube-dl](https://github.com/ytdl-org/youtube-dl#how-do-i-download-a-video-starting-with-a--) and [you-get](https://github.com/soimort/you-get#you-get) quotes the URL in their examples as well.
(P.S. @tonyxyl is renamed to `@lonycc`, as can be seen with https://github.com/tonyxyl/tools.)

Always wrap URL in quotes

---

main.go
request/request.go

By the way,  should we use newer user agent as default options?
e.g. `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36`

feat: Allow users to use specified user agent

---

parser/parser.go

现状：B站的下载文件总是带有“活动作品”4个字
想要达到的效果：不带有“活动作品”
分析： B站的up主因收益，经常选择做活动作品，而活动作品在页面h1里面带有“活动作品”的标签
解决方案：在可能的情况下，取h1的title属性

bilibili去掉活动作品

---

downloader/downloader.go

when there have no streams the progress will panic
```go
lux  "https://www.bilibili.com/bangumi/play/ep257474" 
panic: runtime error: index out of range [0] with length 0
goroutine 1 [running]:
github.com/iawia002/lux/downloader.(*Downloader).Download(0xc000334370, 0xc0003030e0)
/Users/bojue/go/pkg/mod/github.com/iawia002/lux@v0.12.0/downloader/downloader.go:554 +0xbcc
main.download(0xc00019fbf8, {0x7ffeefbffa8c, 0x2e})
/Users/bojue/go/pkg/mod/github.com/iawia002/lux@v0.12.0/main.go:331 +0x95d
main.main.func2(0xc000262e00)
/Users/bojue/go/pkg/mod/github.com/iawia002/lux@v0.12.0/main.go:247 +0x73b
github.com/urfave/cli/v2.(*App).RunContext(0xc0000a7520, {0x1b0a590, 0xc0000280a8}, {0xc000020040, 0x2, 0x2})
/Users/bojue/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:322 +0x7a8 …
```

no streams panic

---

README.md

Fix the link to [lux-dl](https://aur.archlinux.org/packages/lux-dl/)
instead of [lux](https://aur.archlinux.org/packages/lux), which is
described as "POSIX Shell script to easily control brightness on
backlight controllers."

Link to the correct AUR page

---

extractors/facebook/facebook.go
extractors/facebook/facebook_test.go

fix: facebook extractor

---

app/app.go

```
λ  ./lux -j "https://www.douyin.com/video/7069676578136919310"
[
{
"url": "https://www.douyin.com/video/7069676578136919310",
"site": "抖音 douyin.com",
"title": "",
"type": "video",
"streams": {
"default": {
"id": "default",
"quality": "default",
"parts": [
{
"url": "https://aweme.snssdk.com/aweme/v1/play/?video_id=v0200fg10000c8e8ic3c77u9pvoe3jk0\u0026ratio=720p\u0026line=0",
"size": 7997493,
"ext": "mp4"
}
],
"size": 7997493,
"ext": "mp4",
"NeedMux": false
}
},
"caption": null,
"err": null
}
]
```
the url contains unicode \u0026,  use `enc.SetEscapeHTML(false)` to print `&`
https://go.dev/play/p/JlpdFV15_rI

Pretty print correctly formatted url

---

go.mod
go.sum
utils/utils.go
utils/utils_test.go

[gjson 远不如jq 强大，有些取值还是做不到](https://github.com/tidwall/jj/issues/27)
比如要取[这个](https://www.ixigua.com/api/public/videov2/brief/details?group_id=7067848979140051456)里的video_list里的main_url， gjson做不到, 而且搜索下了源代码，目前还没有extractor依赖gjson，建议替换
gojq 可以，并且和jq语法一直，提供命令行，方便测试
[kuaishou json](https://jqplay.org/s/rSAgv0kIgc)

Remove gjson in favor of gojq

---

README.md

The package information locate at https://github.com/iawia002/lux-cask
macOS:
Linux:
Windows: (powershell/cmd/git bash)

docs: add Installation for cask

---

extractors/qq/qq.go

Bugs like:
> Downloading http://v.qq.com/x/page/u3229gcghm6.html error:
> json: cannot unmarshal number 2364254033 into Go struct field .fl.fi.fs of type int

Fix Fs parse failed while video length is too long

---

README.md
app/app.go
downloader/downloader.go

This can speed up bilibili video download.
Bilibili videos are usually divided into 2 fragments (A&V).
Therefore, before this PR, the program uses only 2 threads to download when `-thread 10`.

feat: split-fragment

---

extractors/mgtv/mgtv.go
extractors/pornhub/pornhub.go
extractors/xinpianchang/xinpianchang.go

Remove Redundant Character Escape in RegExp

---

.github/workflows/stream_rumble.yml
README.md
app/register.go
extractors/rumble/rumble.go
extractors/rumble/rumble_test.go

Support for Rumble https://github.com/iawia002/lux/issues/1188

Add Rumble extractor

---

.github/workflows/stream_zingmp3.yml
README.md
app/register.go
extractors/zingmp3/zingmp3.go
extractors/zingmp3/zingmp3_test.go
go.mod
go.sum
utils/utils.go

Support download for https://zingmp3.vn/

feat: add zingmp3 extractor

---

extractors/bilibili/bilibili.go
extractors/bilibili/types.go

The previous API URL still works, but it now only returns an empty `subtitle_url`, making `lux` unable to download subtitles anymore. The JSON file returned by the new API URL has changed a bit, but not much as far as subtitles are concerned, and the `bilibiliWebInterface` struct is only used once on the following line, so I don't think there will be unexpected side effects.
https://github.com/iawia002/lux/blob/90109ff79f7c6a798c35a2d5c9b8c570a616f226/extractors/bilibili/bilibili.go#L508

Updated API for requesting subtitles from bilibili

---

extractors/bilibili/bilibili.go

The format of the JSON data embedded in bangumi pages has been changed, fortunately not by a lot in terms of what I had to change in the parsing code. I tested a couple of ep and ss URLs, it worked for all of them.

Updated Bilibili bangumi extractor due to an API change

---

app/app.go
downloader/downloader.go

I think this option is more user friendly than choosing audio stream from streams output.
I tested it out with youtube videos, and it's working pretty fine.

Add --audio-only flag

---

downloader/downloader.go
extractors/bilibili/bilibili.go
extractors/bilibili/bilibili_test.go
extractors/bilibili/types.go

Bilibili Festival

---

extractors/bilibili/bilibili.go

针对bilibili 合集下载的时候如果文件名相同会被跳过的问题
issues:
fix: #1314 
fix: #1246 
效果如下：

解决 bilibili 下载playlist时 LUX will skip files with same names

---

request/request.go

I got a redirect loop when trying to download a video from rumble. I looked in chrome developer tools at the requests and there were a few cookies being set on the first redirect, that i guessed were not being sent by the default go client.
Adding a cookie jar fixed the issue for me.

fixes rumble loop

---

utils/ffmpeg.go

windows os 下，即使ffmpge.exe放當前目錄也無法找到。

解決: windows os 下，嘗試在當前目錄中查找ffmpeg失敗

---

README.md
extractors/ixigua/ixigua.go
extractors/ixigua/types.go
extractors/xiaohongshu/xiaohongshu_test.go

重写iXigua(Toutiao)视频获取方式

---

.github/workflows/stream_bitchute.yml
README.md
app/register.go
extractors/bitchute/bitchute.go
extractors/bitchute/bitchute_test.go

Add Bitchute extractor

---

extractors/rumble/rumble.go
extractors/rumble/rumble_test.go

Had an issue where newly uploaded videos had no streams. The json file returned has a new section in that is called tar, its a m3u8 files for each resolution that include chunks of a mp2t file.
Updated the library to correctly get the new type of stream

fix no streams for newly published rumble videos
